spring:
  profiles:
    active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mindplates.com:3306/shareplates?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: shareplates
    password: dhao1234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  redis:
    host: mindplates.com
    port: 6379
    password: dhao1234
  mail:
    host: mindplates.com
    port: 20000
    protocol: smtp
    username: shareplates
    password: enterpr1se!
    default-encoding: UTF-8
  session:
    store-type: redis
    redis:
      cluster:
        nodes: mindplates.com:6379
      flush-mode: on-save # Sessions flush mode.
      namespace: spring:session # Namespace for keys used to store sessions.
  messages:
    basename: messages/message
    encoding: UTF-8
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  servlet:
    multipart:
     enabled: true
     file-size-threshold: 2KB
     max-file-size: 200MB
     max-request-size: 215MB

logging:
  level: 
    com.msws.shareplates: debug
    
file:
  upload-dir: c:/fileupload/
  allowed-extension: txt,pdf

shareplates:
  locale:
    default: ko
  corsUrls: http://localhost:3000, http://mindplates.com:3000
  url: http://www.mindplates.com
  web-url: http://localhost:3000
  mail:
    senderName: noreply@mindplates.com
server:
  servlet:
    session:
      timeout: 6000 # Session timeout. If a duration suffix is not specified, seconds is used.
      
oauth:
  kakao:
    host: https://kauth.kakao.com
    api-host: https://kapi.kakao.com
    token-endpoint: /oauth/token
    userinfo-endpoint: /v2/user/me
    client-id: 863525fbdd02a15ac03536bbfcf0151d
    redirect-uri: http://localhost:8080/oauth/kakao/token
    
slack:
  url: https://hooks.slack.com/services/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
    
---
spring:
  profiles: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.102:3306/shareplates?serverTimezone=UTC&characterEncoding=UTF-8
  mail:
    host: 192.168.56.102
file:
  upload-dir: /data/upload
shareplates:
  locale:
    default: ko
  corsUrls: http://localhost:3000, http://mindplates.com:3000
  url: http://www.mindplates.com
  web-url: /
  mail:
    senderName: noreply@mindplates.com
logging:
  level: 
    com.msws.shareplates: error
oauth:
  kakao:
    host: https://kauth.kakao.com
    api-host: https://kapi.kakao.com
    token-endpoint: /oauth/token
    userinfo-endpoint: /v2/user/me
    client-id: 863525fbdd02a15ac03536bbfcf0151d
    redirect-uri: http://mindplates.com/oauth/kakao/token
    