spring:
  profiles:
    active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mindplates.com:3306/shareplates?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: shareplates
    password: dhao1234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  redis:
    host: mindplates.com
    port: 6379
    password: dhao1234
  mail:
    host: mindplates.com
    port: 20000
    protocol: smtp
    username: shareplates
    password: enterpr1se!
    default-encoding: UTF-8
  session:
    store-type: redis
    redis:
      cluster:
        nodes: mindplates.com:6379
      flush-mode: on-save # Sessions flush mode.
      namespace: spring:session # Namespace for keys used to store sessions.
server:
  servlet:
    session:
      timeout: 6000 # Session timeout. If a duration suffix is not specified, seconds is used.
shareplates:
  corsUrl : http://localhost:3000
  url: http://www.mindplates.com
  mail:
    senderName: noreply@mindplates.com